server:
  port: 8084

eureka:
  instance:
    appname: Dynamic-properties
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

dynamic-properties:
  path: "file:///conf.properties"